version: "3.7"

services:
    database:
        image: mysql:5.7
        container_name: bookstore_db
        environment:
            MYSQL_ROOT_PASSWORD: Clarusway_1
            MYSQL_DATABASE: bookstore_db
            MYSQL_USER: clarusway
            MYSQL_PASSWORD: Clarusway_1
        networks:
            - booknet
    bookstore_app:
        container_name: bookstore_app
        build: .
        restart: always
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - booknet

networks:
    booknet:
        driver: bridge